# Kismet config file

# Bluetooth capture source (internal Pi 5 Bluetooth)

source=bluetooth:hci0


# Wi-Fi capture source (Panda PAU0F AXE3000)

source=wlan1:name=wifi0


# Log directory

log_prefix=/var/log/kismet


# GPS configuration
gps=gpsd:host=localhost,port=2947




# Include the httpd config options
# %E is expanded to the system etc path configured at install
include=%E/kismet_httpd.conf

# Include the memory tuning options
include=%E/kismet_memory.conf

# Include the alert config options
include=%E/kismet_alerts.conf

# Include 802.11-specific options
include=%E/kismet_80211.conf

# Include logging options
include=%E/kismet_logging.conf

# Include filter options
include=%E/kismet_filter.conf

# Include UAV drone configs
include=%E/kismet_uav.conf


# Path that helper and capture binaries 
helper_binary_path=%B


# Kismet can announce itself via broadcast packets for automatic remote capture
server_announce=false
server_announce_address=0.0.0.0
server_announce_port=2501


# Kismet can accept connections from remote capture datasources
remote_capture_enabled=true
remote_capture_listen=127.0.0.1
remote_capture_port=3501


# Hop channels if possible
channel_hop=true

# How fast do we hop channels?  Time can be hops/second or hops/minute.
channel_hop_speed=5/sec

# If we have multiple sources with the same type, Kismet can try to split
split_source_hopping=true

# Should Kismet scramble the channel list
randomized_hopping=true

# Should sources be re-opened when they encounter an error?
retry_on_source_error=true


# Number of sources before we trigger staggered startup
source_stagger_threshold=16

# Number of sources to launch as each group
source_launch_group=8

# How long do we delay, in seconds, between opening groups of sources?
source_launch_delay=10

# Should we override remote sources timestamps? 
override_remote_timestamp=true



# Do we allow plugins to be used?  
allowplugins=true


# OUI file, generated by tools/create_manuf_db.py
ouifile=%S/kismet/kismet_manuf.txt.gz

# ICAO file, generated by tools/create_icao_db.py
icaofile=%S/kismet/kismet_adsb_icao.txt.gz




# Is transmission of the keys to the client allowed? 
allowkeytransmit=true

# Where state info, etc, is stored.  
configdir=%h/.kismet/


